import { Question } from './types';

export const QUESTION_BANK: Question[] = [
  // ==========================================
  // MUST-ASK TIER (1-10)
  // ==========================================
  {
    id: 'purpose',
    tier: 'must_ask',
    category: 'core',
    title: 'What is the primary purpose of this loan?',
    helpText: 'Lenders evaluate risk differently depending on whether debt is productive or consumable.',
    type: 'select',
    options: [
      { value: 'wedding', label: 'Wedding / Family Ceremony', sublabel: 'Social event / celebratory' },
      { value: 'education', label: 'Higher Education', sublabel: 'Tuition / living expenses' },
      { value: 'medical', label: 'Medical Treatment / Emergency', sublabel: 'Healthcare procedure' },
      { value: 'vehicle', label: 'Vehicle Purchase (Two-Wheeler / EV / Car)', sublabel: 'Commute or commercial vehicle' },
      { value: 'business_working_capital', label: 'Business Working Capital / Stock', sublabel: 'Inventory, daily turnover' },
      { value: 'business_asset', label: 'Business Asset / Equipment', sublabel: 'Machinery, shop expansion' },
      { value: 'home_purchase', label: 'Home / Flat Purchase', sublabel: 'Residential property acquisition' },
      { value: 'home_renovation', label: 'Home Renovation / Improvement', sublabel: 'Repairs or extension' },
      { value: 'debt_consolidation', label: 'Debt Consolidation', sublabel: 'Combine high-interest debts' },
      { value: 'other', label: 'Other Personal Expense', sublabel: 'Travel or general consumption' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Determines product category eligibility, tax benefits, and potential income-generating debt uplift.',
  },
  {
    id: 'amountWanted',
    tier: 'must_ask',
    category: 'core',
    title: 'How much money are you looking to borrow?',
    helpText: 'Enter the exact principal amount in Indian Rupees (₹).',
    type: 'currency',
    min: 10000,
    max: 100000000,
    step: 10000,
    placeholder: 'e.g. 8,00,000',
    appliesIf: () => true,
    informationGainReason: 'Anchor input required to test against lender FOIR ceilings and calculate live EMI outflows.',
  },
  {
    id: 'loanProductWanted',
    tier: 'must_ask',
    category: 'core',
    title: 'Which loan product are you seeking?',
    helpText: 'We will suggest a cheaper product if your profile qualifies for collateralized alternatives.',
    type: 'select',
    options: [
      { value: 'personal', label: 'Personal Loan (Unsecured)', sublabel: 'Quick disbursement, no collateral' },
      { value: 'home', label: 'Home Loan', sublabel: 'Subsidized mortgage rates for residential property' },
      { value: 'lap', label: 'Loan Against Property (LAP)', sublabel: 'Low interest mortgage on owned property' },
      { value: 'gold', label: 'Gold Loan', sublabel: 'Pledge jewellery/coins for instant low-rate cash' },
      { value: 'vehicle_tw', label: 'Two-Wheeler / EV Loan', sublabel: 'Hypothecated asset loan' },
      { value: 'business_secured', label: 'Secured Business Loan', sublabel: 'Collateralized commercial loan' },
      { value: 'business_unsecured', label: 'Unsecured Business Loan', sublabel: 'Working capital based on turnover' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Allows the user to specify preference while enabling the engine to benchmark against optimal product.',
  },
  {
    id: 'employmentType',
    tier: 'must_ask',
    category: 'core',
    title: 'What is your primary source of employment & income?',
    helpText: 'Lender documentation and risk appetite vary drastically between salaried and informal workers.',
    type: 'select',
    options: [
      { value: 'salaried', label: 'Salaried Professional', sublabel: 'Monthly salary credited directly to bank account' },
      { value: 'self_employed_itr', label: 'Self-Employed (Files Income Tax Returns / GST)', sublabel: 'Business owner, professional with formal books' },
      { value: 'self_employed_cash', label: 'Self-Employed (Cash / Informal Accounts)', sublabel: 'Shopkeeper, vendor, trader with minimal paper trail' },
      { value: 'gig_informal', label: 'Gig Worker / Informal Earner', sublabel: 'Delivery partner, artisan, driver, tailor' },
      { value: 'unemployed', label: 'Currently Unemployed / No Active Income', sublabel: 'Seeking debt between employments' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Sets the foundational baseline FOIR limit (55% for stable salaried down to 35% for informal).',
  },
  {
    id: 'monthlyIncome',
    tier: 'must_ask',
    category: 'core',
    title: 'What is your net take-home monthly income?',
    helpText: 'Salaried: in-hand bank credit after taxes and deductions. Informal/Self-Employed: average monthly cash earnings.',
    type: 'currency',
    min: 5000,
    max: 5000000,
    step: 5000,
    placeholder: 'e.g. 1,10,000',
    appliesIf: (answers) => answers.employmentType !== 'self_employed_cash' && answers.employmentType !== 'gig_informal',
    informationGainReason: 'The denominator for all FOIR and discretionary cashflow capacity calculations.',
  },
  {
    id: 'incomeRange',
    tier: 'must_ask',
    category: 'informal',
    title: 'What is your monthly net income range (worst month to best month)?',
    helpText: 'Informal cashflow fluctuates. Give us your realistic monthly minimum and peak income.',
    type: 'currency_range',
    min: 5000,
    max: 1000000,
    step: 2000,
    placeholder: 'Min and Max monthly earnings',
    appliesIf: (answers) => answers.employmentType === 'self_employed_cash' || answers.employmentType === 'gig_informal',
    informationGainReason: 'Captures earnings volatility for informal earners, anchoring safe capacity to the conservative 30th percentile.',
  },
  {
    id: 'existingEmis',
    tier: 'must_ask',
    category: 'core',
    title: 'Total monthly EMIs you currently pay across all existing loans',
    helpText: 'Include credit card EMIs, car loans, personal loans, app loans, and gold loans. Enter "0" if none.',
    type: 'currency',
    min: 0,
    max: 2000000,
    step: 1000,
    placeholder: '0 if debt-free',
    appliesIf: () => true,
    informationGainReason: 'Subtracted directly from FOIR capacity; high existing EMIs trigger conservative borrowing ceilings.',
  },
  {
    id: 'essentialExpenses',
    tier: 'must_ask',
    category: 'core',
    title: 'Essential household living expenses per month (excluding EMIs)',
    helpText: 'Include house rent, groceries, school fees, utility bills, insurance, and medical essentials.',
    type: 'currency',
    min: 0,
    max: 2000000,
    step: 1000,
    placeholder: 'e.g. 28,000',
    appliesIf: () => true,
    informationGainReason: 'Critical for the Safe-to-Carry calculation; separates realistic cashflow from raw banking formula.',
  },
  {
    id: 'age',
    tier: 'must_ask',
    category: 'core',
    title: 'What is your age?',
    helpText: 'Banks cap loan tenure so repayment finishes before typical retirement age (60–65 years).',
    type: 'number',
    min: 18,
    max: 75,
    placeholder: 'e.g. 29',
    appliesIf: () => true,
    informationGainReason: 'Constrains maximum permissible tenure for long-duration loans like mortgages and LAP.',
  },
  {
    id: 'creditScore',
    tier: 'must_ask',
    category: 'core',
    title: 'What is your CIBIL / Experian credit score?',
    helpText: 'If you have not checked or have no bureau history, select "I do not know". We will never penalize you as worst-case.',
    type: 'credit_score',
    min: 300,
    max: 900,
    placeholder: 'e.g. 780',
    appliesIf: () => true,
    informationGainReason: 'Shifts product pricing across Tier 1 (750+), Tier 2 (650-749), or conservative unverified tier.',
  },
  {
    id: 'collateral',
    tier: 'must_ask',
    category: 'core',
    title: 'Do you have any unencumbered collateral available to pledge?',
    helpText: 'Pledging property, gold, or fixed deposits slashes borrowing rates from 18%+ to under 11%.',
    type: 'select',
    options: [
      { value: 'none', label: 'No Collateral (Unsecured Loan)', sublabel: 'Rely purely on salary slip or income tax returns' },
      { value: 'property', label: 'Residential or Commercial Property', sublabel: 'Clear title deed, unencumbered (qualifies for LAP)' },
      { value: 'gold', label: 'Gold Jewellery or Coins', sublabel: 'Immediate physical gold pledge' },
      { value: 'fd', label: 'Fixed Deposit (FD)', sublabel: 'Lien against bank deposit' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Highest single leverage question in the entire questionnaire; routes borrowers from predatory rates to prime secured debt.',
  },

  // ==========================================
  // ADDITIONAL ADAPTIVE TIER
  // ==========================================

  // High leverage follow-up for Collateral (Ravi's path)
  {
    id: 'collateralValue',
    tier: 'additional',
    category: 'self_employed',
    title: 'Estimated market value of your collateral (property, gold, or FD)',
    helpText: 'Property qualifies up to 65% LTV; Gold up to 75% LTV; FD up to 90% LTV.',
    type: 'currency',
    min: 50000,
    max: 500000000,
    step: 50000,
    placeholder: 'e.g. 45,00,000',
    appliesIf: (answers) => answers.collateral !== undefined && answers.collateral !== 'none',
    informationGainReason: 'Enforces statutory RBI Loan-to-Value ceilings on secured credit facilities.',
  },

  // Income stability across all profiles
  {
    id: 'incomeStability',
    tier: 'additional',
    category: 'all',
    title: 'How long have you been in your current job or business?',
    helpText: 'Lenders provide 10% more FOIR headroom and lower interest rates for track records exceeding 2 years.',
    type: 'select',
    options: [
      { value: 'gt_2_years', label: 'More than 2 years (Stable)', sublabel: 'Consistent employer or business vintage' },
      { value: 'lt_2_years', label: '6 months to 2 years', sublabel: 'Moderate stability or recent career change' },
      { value: 'lt_6_months', label: 'Under 6 months / Probationary', sublabel: 'High lender scrutiny on probation' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Directly adjusts lender FOIR cap between 55% (stable) and 45% (probationary/unstable).',
  },

  // Bounce history - directly impacts verdict
  {
    id: 'bouncesLast12m',
    tier: 'additional',
    category: 'all',
    title: 'Have you had any EMI, cheque, or ECS/NACH bounces in the last 12 months?',
    helpText: 'Even an accidental bounce signals banking friction to credit underwriters and drops your borrowing capacity.',
    type: 'select',
    options: [
      { value: 0, label: 'Zero bounces (Clean track record)', sublabel: 'All automated debits cleared on time' },
      { value: 1, label: '1 bounce in the last 12 months', sublabel: 'Single missed or delayed automated deduction' },
      { value: 2, label: '2 or more bounces', sublabel: 'Multiple banking clearance failures' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Forces an 8% FOIR cap reduction and +100 bps rate penalty, triggering Don\'t Borrow if obligations are already stretched.',
  },

  // Emergency savings cushion
  {
    id: 'emergencySavingsMonths',
    tier: 'additional',
    category: 'all',
    title: 'How many months of essential living expenses do you have in emergency savings?',
    helpText: 'If you have less than 3 months of emergency buffer, our model elevates your safety cushion from 15% to 20%.',
    type: 'select',
    options: [
      { value: 0, label: 'Less than 1 month / Nil', sublabel: 'Living month-to-month on current earnings' },
      { value: 2, label: '1 to 2 months', sublabel: 'Thin emergency reserve' },
      { value: 4, label: '3 to 5 months', sublabel: 'Comfortable financial cushion' },
      { value: 6, label: '6 months or more', sublabel: 'Robust emergency safety net' },
    ],
    appliesIf: () => true,
    informationGainReason: 'Determines whether the safe-to-carry model imposes an elevated 20% savings buffer to prevent insolvency.',
  },

  // Co-applicant income
  {
    id: 'coApplicantIncome',
    tier: 'additional',
    category: 'all',
    title: 'Co-applicant / spouse net monthly income (if applying jointly)',
    helpText: 'Banks count 100% of joint income. Borrower Copilot counts 70% for safe cashflow to maintain a safety margin.',
    type: 'currency',
    min: 0,
    max: 2000000,
    step: 2000,
    placeholder: '0 if solo applicant',
    appliesIf: () => true,
    informationGainReason: 'Expands lender approval ceiling while applying a realistic 30% haircut to safe family cashflow.',
  },

  // Upcoming large expense
  {
    id: 'upcomingLargeExpense',
    tier: 'additional',
    category: 'all',
    title: 'Any known large lump-sum expenses planned in the next 12 months?',
    helpText: 'e.g. Annual school fees, medical surgery, family function, security deposit. Enter "0" if none.',
    type: 'currency',
    min: 0,
    max: 10000000,
    step: 5000,
    placeholder: '0 if none',
    appliesIf: () => true,
    informationGainReason: 'Amortized over 12 months and subtracted directly from monthly debt servicing capacity.',
  },

  // Salaried: Credit card utilization
  {
    id: 'creditCardUtilisation',
    tier: 'additional',
    category: 'salaried',
    title: 'What percentage of your total credit card limit do you actively utilize?',
    helpText: 'Revolving card balances above 40% signal liquidity tightness and increase retail loan quotes by ~0.75%.',
    type: 'select',
    options: [
      { value: 15, label: 'Under 30% (Low / Ideal)', sublabel: 'Disciplined card usage with full monthly payoffs' },
      { value: 50, label: '30% to 60% (Moderate)', sublabel: 'Carrying occasional rolling card balances' },
      { value: 80, label: 'Above 60% (High)', sublabel: 'Frequently maxing out credit card limits' },
    ],
    appliesIf: (answers) => answers.employmentType === 'salaried',
    informationGainReason: 'Applies a 0.75% rate penalty if utilization breaches 40%, reflecting bureau risk flags.',
  },

  // Self-Employed: Business incremental income test
  {
    id: 'businessProjectedIncome',
    tier: 'additional',
    category: 'self_employed',
    title: 'Expected incremental monthly profit generated by this loan?',
    helpText: 'If this loan directly buys inventory or machinery that produces revenue, enter realistic monthly gains.',
    type: 'currency',
    min: 0,
    max: 1000000,
    step: 5000,
    placeholder: 'e.g. 20,000',
    appliesIf: (answers) =>
      answers.purpose === 'business_working_capital' || answers.purpose === 'business_asset',
    informationGainReason: 'Applies productive debt uplift test (recognizes 50% of income up to +10% FOIR cap boost).',
  },

  // Self-Employed / Informal: Income Volatility
  {
    id: 'variableIncomeShare',
    tier: 'additional',
    category: 'informal',
    title: 'How much does your monthly earnings vary from average?',
    helpText: 'High variation demands a stronger safety buffer to prevent default during lean months.',
    type: 'select',
    options: [
      { value: 10, label: 'Predictable (fluctuates under 15%)', sublabel: 'Steady seasonal demand' },
      { value: 35, label: 'Moderate (fluctuates 15% to 40%)', sublabel: 'Noticeable lean and peak periods' },
      { value: 60, label: 'Highly unpredictable (fluctuates over 40%)', sublabel: 'Volatile daily or weekly wages' },
    ],
    appliesIf: (answers) =>
      answers.employmentType === 'self_employed_cash' ||
      answers.employmentType === 'gig_informal' ||
      answers.employmentType === 'self_employed_itr',
    informationGainReason: 'Applies a 15% haircut to safe borrowing capacity to protect against seasonal lean periods.',
  },

  // Informal: Existing App Loan APR (Anita's key question)
  {
    id: 'existingAppLoanApr',
    tier: 'additional',
    category: 'informal',
    title: 'What annual interest rate (APR) are you paying on any existing app or informal loans?',
    helpText: 'Instant loan apps and informal moneylenders frequently charge 30% to 50%+ annualized interest.',
    type: 'select',
    options: [
      { value: 0, label: 'No app loans or informal debt', sublabel: 'Only formal bank debt or debt-free' },
      { value: 18, label: 'Around 14% to 20% APR', sublabel: 'Standard NBFC personal loan' },
      { value: 36, label: '30% or higher APR (Instant app loans / Daily finance)', sublabel: 'High-cost short term app borrowing' },
    ],
    appliesIf: (answers) =>
      answers.employmentType === 'gig_informal' ||
      answers.employmentType === 'self_employed_cash' ||
      answers.purpose === 'debt_consolidation',
    informationGainReason: 'Detects predatory debt exposure (>=24%) and empowers the borrower with fair market counter-benchmarks.',
  },

  // Existing lender offers
  {
    id: 'existingOfferRate',
    tier: 'additional',
    category: 'all',
    title: 'Have you already received an interest rate quote from a lender?',
    helpText: 'If a bank or NBFC has given you a preliminary quote, enter the interest rate to see if it is fair.',
    type: 'number',
    min: 5,
    max: 50,
    step: 0.1,
    placeholder: 'e.g. 14.5%',
    appliesIf: () => true,
    informationGainReason: 'Enables direct comparative disclosure in the Negotiation Card: "You were quoted X%, fair is Y%".',
  },
];
